# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
apt_packages:
    - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: oldrel

before_deploy: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
